version: '3'

services:
  app:
    image: blueberrymozart/test-c2c
    build:
      context: .
    ports:
    - 3000:3000

  db:
    image: mongo:3.4-jessie
    volumes:
    - ../db/seedData:/seedData
    ports:
    - 27017:27017
    - 28017:28017
